# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70a503df8905a246fa3cb21407b106a088dbbe6145cbc6ff8c1e3ab3181ea3ec716fd98a23fc1c06a29d435007d90a524d6cf9f274655fbd7331f591f5b639c4

test:
  secret_key_base: 221d96f7385a0a7ed556214efaf4c9f20ce2f5f33d13ab551e175c4263600b1dad1d06acd34b163cdb3e4efc43e0e38f656dae1253c3656cc8e752c2374992cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
